<?php

/**
 * PHP version 7
 *
 * @category  Risecommerce
 * @package   Risecommerce_VideoGallery
 * @author    Risecommerce <magento@risecommerce.com>
 * @copyright 2019 This file was generated by Risecommerce
 * @license   https://www.risecommerce.com  Open Software License (OSL 3.0)
 * @link      https://www.risecommerce.com
 */

namespace Risecommerce\VideoGallery\Model;

use Magento\Framework\Model\AbstractModel;

class Video extends AbstractModel
{
    /**
     * Initialize
     *
     * @return Null
     */
    protected function _construct()
    {
        $this->_init(\Risecommerce\VideoGallery\Model\ResourceModel\Video::class);
    }

    public function getStores()
    {
        return explode(',', $this->getData('stores'));

    }

    public function getCustomerGroups()
    {
        return explode(',', $this->getData('customer_groups'));
    }
}
