<?php
/**
 * PHP version 7
 *
 * @category  Risecommerce
 * @package   Risecommerce_VideoGallery
 * @author    Risecommerce <magento@risecommerce.com>
 * @copyright 2019 This file was generated by Risecommerce
 * @license   https://www.risecommerce.com  Open Software License (OSL 3.0)
 * @link      https://www.risecommerce.com
 */
namespace Risecommerce\VideoGallery\Helper;

class Data extends \Magento\Framework\App\Helper\AbstractHelper
{
    const VIDEO_TITLE = 'video/general/display_title';
    public function getTitle()
    {
        return $this->scopeConfig->getValue(
            self::VIDEO_TITLE,
            \Magento\Store\Model\ScopeInterface::SCOPE_STORE
        );
    }
}
