<?php

/**
 * PHP version 7
 *
 * @category  Risecommerce
 * @package   Risecommerce_VideoGallery
 * @author    Risecommerce <magento@risecommerce.com>
 * @copyright 2019 This file was generated by Risecommerce
 * @license   https://www.risecommerce.com  Open Software License (OSL 3.0)
 * @link      https://www.risecommerce.com
 */
namespace Risecommerce\VideoGallery\Ui\Component\Listing\Column;

use Magento\Framework\View\Element\UiComponent\ContextInterface;
use Magento\Framework\View\Element\UiComponentFactory;
use Magento\Ui\Component\Listing\Columns\Column;
use Magento\Framework\UrlInterface;


class Actions extends Column
{
    /**
     * Url path
     */
    const VIDEO_URL_PATH_EDIT = 'risecommerce_videogallery/video/edit';
    const VIDEO_URL_PATH_DELETE = 'risecommerce_videogallery/video/delete';

    /**
     * UrlInterface Variable
     *
     * @var UrlInterface
     */
    protected $urlBuilder;

    /**
     * Editurl Variable
     *
     * @var string
     */
    protected $editUrl;

    /**
     * Initialize
     *
     * @param ContextInterface   $context            Initialize ContextInterface
     * @param UiComponentFactory $uiComponentFactory Initialize UiComponentFactory
     * @param UrlInterface       $urlBuilder         Initialize UrlInterface
     * @param array              $components         Initialize components
     * @param array              $data               Initialize data
     * @param string             $editUrl            Initialize editurl
     */
    public function __construct(
        ContextInterface $context,
        UiComponentFactory $uiComponentFactory,
        UrlInterface $urlBuilder,
        array $components = [],
        array $data = [],
        $editUrl = self::VIDEO_URL_PATH_EDIT
    ) {
        $this->urlBuilder = $urlBuilder;
        $this->editUrl = $editUrl;
        parent::__construct($context, $uiComponentFactory, $components, $data);
    }

    /**
     * Prepare Data Source
     *
     * @param array $dataSource datasource
     *
     * @return array
     */
    public function prepareDataSource(array $dataSource)
    {
        if (isset($dataSource['data']['items'])) {
            foreach ($dataSource['data']['items'] as & $item) {
                $name = $this->getData('name');
                if (isset($item['id'])) {
                    $item[$name]['edit'] = [
                        'href' => $this->urlBuilder->getUrl($this->editUrl, ['id' => $item['id']]),
                        'label' => __('Edit')
                    ];
                    $item[$name]['delete'] = [
                        'href' => $this->urlBuilder->getUrl(self::VIDEO_URL_PATH_DELETE, ['id' => $item['id']]),
                        'label' => __('Delete'),
                        'confirm' => [
                            'title' => __('Delete'),
                            'message' => __('Are you sure you wan\'t to delete a record?')
                        ]
                    ];
                }
            }
        }

        return $dataSource;
    }
}
