<?php

/**
 * PHP version 7
 *
 * @category  Risecommerce
 * @package   Risecommerce_VideoGallery
 * @author    Risecommerce <magento@risecommerce.com>
 * @copyright 2019 This file was generated by Risecommerce
 * @license   https://www.risecommerce.com  Open Software License (OSL 3.0)
 * @link      https://www.risecommerce.com
 */

namespace Risecommerce\VideoGallery\Controller\Adminhtml\Video;

use Magento\Backend\App\Action;
use Magento\TestFramework\ErrorLog\Logger;
use Magento\Framework\Filesystem\Driver\File;

class Delete extends \Magento\Backend\App\Action
{

    protected $videoLoader;

    protected $fileSystem;
    /**
     * @var File
     */
    private $file;

    /**
     * Delete constructor.
     * @param \Magento\Backend\App\Action\Context $context
     * @param \Risecommerce\VideoGallery\Model\Video $videoLoader
     * @param \Magento\Framework\Filesystem $fileSystem
     * @param File $file
     */
    public function __construct(
        \Magento\Backend\App\Action\Context $context,
        \Risecommerce\VideoGallery\Model\Video $videoLoader,
        \Magento\Framework\Filesystem $fileSystem,
        File $file
    ) {
        parent::__construct($context);
        $this->videoLoader = $videoLoader;
        $this->fileSystem = $fileSystem;
        $this->file = $file;
    }

    /**
     * {@inheritdoc}
     *
     * @return NUll
     */
    protected function _isAllowed()
    {
        return $this->_authorization->isAllowed('Risecommerce_VideoGallery::delete');
    }

    /**
     * Delete action
     *
     * @return \Magento\Framework\Controller\ResultInterface
     */
    public function execute()
    {
        $id = $this->getRequest()->getParam('id');
        /**
         * Delete action
         *
         * @var \Magento\Backend\Model\View\Result\Redirect $resultRedirect
         */
        $resultRedirect = $this->resultRedirectFactory->create();
        if ($id) {
            try {
                $model = $this->videoLoader;
                $data = $model->load($id);
                //Delete Image From folder
                $filename = $data->getFile();
                $fileSystem = $this->fileSystem;
                $mediaPath = $fileSystem
                    ->getDirectoryRead(\Magento\Framework\App\Filesystem\DirectoryList::MEDIA)
                    ->getAbsolutePath('/risecommerce/video_gallery/');
                if ($filename && $this->file->isExists($mediaPath . $filename)) {
                    $this->file->deleteFile($mediaPath . $filename);
                }

                $model->delete();
                $this->messageManager->addSuccess(__('The Video has been deleted.'));
                return $resultRedirect->setPath('*/*/');
            } catch (\Exception $e) {
                $this->messageManager->addError($e->getMessage());
                return $resultRedirect->setPath('*/*/edit', ['id' => $id]);
            }
        }
        $this->messageManager->addError(__('We can\'t find a Video to delete.'));
        return $resultRedirect->setPath('*/*/');
    }
}
