<?php

/**
 * PHP version 7
 *
 * @category  Risecommerce
 * @package   Risecommerce_VideoGallery
 * @author    Risecommerce <magento@risecommerce.com>
 * @copyright 2019 This file was generated by Risecommerce
 * @license   https://www.risecommerce.com  Open Software License (OSL 3.0)
 * @link      https://www.risecommerce.com
 */
namespace Risecommerce\VideoGallery\Controller\Adminhtml\Video;

class NewAction extends \Magento\Backend\App\Action
{
    /**
     * ResultForwardFactory
     *
     * @var \Magento\Backend\Model\View\Result\Forward
     */
    protected $resultForwardFactory;

    /**
     * Initialization
     *
     * @param Action\Context $context              Initialize context
     * @param ForwardFactory $resultForwardFactory Initialize Forwardfactory
     */
    public function __construct(
        \Magento\Backend\App\Action\Context $context,
        \Magento\Backend\Model\View\Result\ForwardFactory $resultForwardFactory
    ) {
        $this->resultForwardFactory = $resultForwardFactory;
        parent::__construct($context);
    }

    /**
     * {@inheritdoc}
     *
     * @return NUll
     */
    protected function _isAllowed()
    {
        return $this->_authorization->isAllowed('Risecommerce_VideoGallery::save');
    }

    /**
     * Forward to edit
     *
     * @return \Magento\Backend\Model\View\Result\Forward
     */
    public function execute()
    {
        /**
         * Execute Method
         *
         * @var    \Magento\Backend\Model\View\Result\Forward $resultForward
         * @return path
         */
        $resultForward = $this->resultForwardFactory->create();
        return $resultForward->forward('edit');
    }
}
