<?php

/**
 * PHP version 7
 *
 * @category  Risecommerce
 * @package   Risecommerce_VideoGallery
 * @author    Risecommerce <magento@risecommerce.com>
 * @copyright 2019 This file was generated by Risecommerce
 * @license   https://www.risecommerce.com  Open Software License (OSL 3.0)
 * @link      https://www.risecommerce.com
 */

namespace Risecommerce\VideoGallery\Model\ResourceModel\Video;

use Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection;


class Collection extends AbstractCollection
{

    /**
     * Id Initialize
     *
     * @var string
     */
    protected $_idFieldName = 'id';

    /**
     * Define resource model
     *
     * @return void
     */
    protected function _construct()
    {
        $this->_init(\Risecommerce\VideoGallery\Model\Video::class, \Risecommerce\VideoGallery\Model\ResourceModel\Video::class);
    }

    public function addStoreFilter($value)
    {
        $condition = $this->getConnection()->prepareSqlCondition('stores', ['finset' => $value]);
        $this->getSelect()->where(sprintf('(%s OR stores = "0")', $condition));
        return $this;
    }

    public function addCustomerGroups($value)
    {
        $condition = $this->getConnection()->prepareSqlCondition('customer_groups', ['finset' => $value]);
        $this->getSelect()->where(sprintf('(%s OR customer_groups = "all")', $condition));
        return $this;
    }
}
