<?php

/**
 * PHP version 7
 *
 * @category  Risecommerce
 * @package   Risecommerce_VideoGallery
 * @author    Risecommerce <magento@risecommerce.com>
 * @copyright 2019 This file was generated by Risecommerce
 * @license   https://www.risecommerce.com  Open Software License (OSL 3.0)
 * @link      https://www.risecommerce.com
 */

namespace Risecommerce\VideoGallery\Controller\Index;
 
use Magento\Framework\App\Action\Context;


class Index extends \Magento\Framework\App\Action\Action
{
    /**
     * @var PageFactory|\Magento\Framework\View\Result\PageFactory
     */
    protected $_resultPageFactory;

    /**
     * Initialize
     *
     * @param Action\Context $context           Initialize Context
     * @param PageFactory    $resultPageFactory Initialize resultfactory
     */
    public function __construct(
        Context $context,
        \Magento\Framework\View\Result\PageFactory $resultPageFactory
    ) {
        $this->_resultPageFactory = $resultPageFactory;
        parent::__construct($context);
    }
 
    /**
     * Redirect to page
     *
     * @return \Magento\Backend\Model\View\Result\Page|\Magento\Backend\Model\View\Result\Redirect
     */
    public function execute()
    {
        $resultPage = $this->_resultPageFactory->create();
        return $resultPage;
    }
}
